export const Url = "https://recep.space/abi/dosyalar/";
export const Thumb = "https://recep.space/thumbs/";
const apiBase = "StartApi.ashx?Platform=Android&ProcessType=";
export const DocUrl =  "https://view.officeapps.live.com/op/embed.aspx?src=https://recep.space/abi/dosyalar/";
export const ico =  "https://spoprod-a.akamaihd.net/files/fabric-cdn-prod_20201207.001/assets/item-types/256/";
export const PhotoUrl = "abi/post/WayBillPhoto.ashx?WayBillId=";
export const NoteUrl = "https://recep.space/abi/post/ArticelNotes.ashx?ArticelId=";
export const AddUrl = "abi/post/AddOrder.ashx?ArticelId=";
export const SaveUrl = "abi/post/AddArticel.ashx?CorpId=";
export const ProductOutUrl = "abi/post/AddWayBill.ashx?CorpId=";
export const UpdateOrderUrl = "abi/post/UpdateOrder.ashx?OrderId=";
export const SaveNoteUrl = "abi/post/AddNotes.ashx";
export const RotateUrl = "abi/post/DosyaSistem/ResimDondur.ashx";
export const DocumentUploadUrl = "abi/post/UploadWayBillOrder.ashx";
export const getArticelsUrl = apiBase+"Articels"
export const MultiMotionUrl = apiBase + "Motion&MotionType=Multi&OrderId=";
export const GetOrderUrl = apiBase + "Orders&ArticelId=";
export const OneMotionUrl = apiBase + "Motion&MotionType=One&OrderId=";
export const DeleteArticelUrl = apiBase+"DeleteArticel&ArticelId=";
export const getFilesUrl = "/abi/post/OrderPictures.ashx?ArticelId=";
export const ProductTypeUrl = "abi/post/ProductType.ashx";
export const SalesTypeUrl = "abi/post/SaleType.ashx";